### PR TITLE
Limit max instances per org

### PR DESCRIPTION
**Pull request by jsenko**
Local AMS will be used by default

### CODE REVIEW

**Comment by EricWittmann** [comment]
Is this ready to go or does it require us to wait for the fleet manager container image to be rebuilt?

**Comment by jsenko** [comment]
Image has been rebuilt a few moments ago, I'll merge this in a minute.

**Comment by jsenko** [comment]
I assume the the new image tag will be picked up, since we started using DeploymentConfigs, right?

**Comment by EricWittmann** [comment]
Yes it should.

**Pull request merged**
