### PR TITLE
Enable authentication for fleet manager

### PR DESCRIPTION
**Pull request by carlesarnal**

### CODE REVIEW

**Comment by riprasad** [comment]
LGTM

**Comment by jsenko** [comment]
Please wait

**Comment by riprasad** [comment]
@jsenko @carlesarnal  what happens to the `TENANT_MANAGER_AUTH_ENABLED` env variable once this is merged?

**Comment by carlesarnal** [comment]
> @jsenko @carlesarnal what happens to the `TENANT_MANAGER_AUTH_ENABLED` env variable once this is merged? are we going to keep it or remove it? currently it's set to `false`

It must be set to true before merging this.

**Pull request merged**
